chore(core): add namespace

diff --git a/core b/core
--- a/core
+++ b/core
@@ -3,23 +3,23 @@
 # Returning a boolean from a bash function
 #   [Solved]: Stack Overflow: https://stackoverflow.com/questions/5431909/returning-a-boolean-from-a-bash-function
 #
-is_docker_installed() {
+docker::is_docker_installed() {
   which docker >> /dev/null 2>&1
   if [ "$?" != "0" ]; then
-    log::debug "[is_docker_installed] Docker not found"
+    log::debug "[docker::is_docker_installed] Docker not found"
     return 1
   fi
 
-  DOCKER_VERSION=$(get_docker_version)
+  DOCKER_VERSION=$(docker::get_docker_version)
   log::info "Docker Installed(version: ${DOCKER_VERSION})"
   return 0
 }
 
-get_docker_version() {
+docker::get_docker_version() {
   echo $(docker version -f {{.Client.Version}})
 }
 
-is_network_exist() {
+docker::is_network_exist() {
   sudo docker network inspect $PACKAGE_DOCKER_DEFAULT_NETWORK >>/dev/null 2>&1
   if [ "$?" = "0" ]; then
     echo "true"
@@ -28,19 +28,19 @@ is_network_exist() {
   fi
 }
 
-create_network() {
+docker::create_network() {
   # sudo docker network inspect $PACKAGE_DOCKER_DEFAULT_NETWORK >>/dev/null 2>&1
   # if [ "$?" != "0" ]; then
   #   sudo docker network create $PACKAGE_DOCKER_DEFAULT_NETWORK
   # fi
 
-  if [ "$(is_network_exist)" = "false" ]; then
+  if [ "$(docker::is_network_exist)" = "false" ]; then
     log::info "Create Network: ${PACKAGE_DOCKER_DEFAULT_NETWORK}"
     sudo docker network create $PACKAGE_DOCKER_DEFAULT_NETWORK >> /dev/null 2>&1
   fi
 }
 
-try_to_remove_podman() {
+docker::try_to_remove_podman() {
   which podman >>/dev/null 2>&1
   if [ "$?" = "0" ]; then
     log::info "Found podman, removing ..."
@@ -54,11 +54,11 @@ try_to_remove_podman() {
   fi
 }
 
-install_docker_core() {
+docker::install_docker_core() {
   # Returning a boolean from a bash function
   #   Useage
-  if is_docker_installed; then
-    create_network
+  if docker::is_docker_installed; then
+    docker::create_network
     return 
   fi
 
@@ -85,11 +85,11 @@ install_docker_core() {
   fi
 }
 
-install_docker_cli_only() {
+docker::install_docker_cli_only() {
   zmicro package install docker-cli
 }
 
-start_docker() {
+docker::start_docker() {
   if [ "$(os::is_macos)" = "true" ]; then
     return
   fi
@@ -105,20 +105,22 @@ start_docker() {
 
   # @TODO create default network
   # sudo docker network create compose-ingress
-  if [ "$(is_network_exist)" = "false" ]; then
+  if [ "$(docker::is_network_exist)" = "false" ]; then
     log::info "Create Network: ${PACKAGE_DOCKER_DEFAULT_NETWORK}"
     sudo docker network create $PACKAGE_DOCKER_DEFAULT_NETWORK >> /dev/null 2>&1
   fi
 }
 
-stop_docker() {
+docker::stop_docker() {
   sudo systemctl stop docker
   sudo systemctl disable docker
 }
 
-remove_docker_core() {
+docker::remove_docker_core() {
   pm remove -y docker-ce docker-ce-cli containerd.io
 }
+
+#######
 
 install() {
   if [ "$(os::is_docker)" = "true" ] || [ "$(os::is_docker_build_env)" = "true" ]; then
@@ -126,7 +128,7 @@ install() {
 
     if [ "$(os::has_command docker)" = "false" ]; then
       log::info "Install Docker CLI Only (with buildx) ..."
-      install_docker_cli_only
+      docker::install_docker_cli_only
 
       log::info "Install Docker CLI BuildX ..."
       zmicro package install docker-buildx
@@ -141,41 +143,40 @@ install() {
     return 
   fi
 
-  try_to_remove_podman
+  docker::try_to_remove_podman
 
-  install_docker_core
+  docker::install_docker_core
 
-  start_docker
+  docker::start_docker
 }
 
 remove() {
-  try_to_remove_podman
+  docker::try_to_remove_podman
 
   # Returning a boolean from a bash function
   #   Useage
-  if ! is_docker_installed; then
+  if ! docker::is_docker_installed; then
     log "Cannot found docker or docker has been already removed before."
     exit 0
   fi
 
   log "Stop Docker Daemon ..."
-  stop_docker
+  docker::stop_docker
 
   log "Remove Docker ..."
-  remove_docker_core
+  docker::remove_docker_core
 }
 
-export -f is_docker_installed
-export -f get_docker_version
-export -f is_network_exist
-export -f create_network
-export -f try_to_remove_podman
-export -f install_docker_core
-export -f start_docker
-export -f stop_docker
-export -f remove_docker_core
+export -f docker::is_docker_installed
+export -f docker::get_docker_version
+export -f docker::is_network_exist
+export -f docker::create_network
+export -f docker::try_to_remove_podman
+export -f docker::install_docker_core
+export -f docker::start_docker
+export -f docker::stop_docker
+export -f docker::remove_docker_core
+export -f docker::install_docker_cli_only
 
 export -f install
 export -f remove
-
-export -f install_docker_cli_only
