ci: add ci

diff --git a/install b/install
--- a/install
+++ b/install
@@ -2,7 +2,8 @@
 
 help() {
   echo "Usage:"
-  echo "  zmicro package install docker"
+  echo "  zmicro package install ${PACKAGE_NAME} <args...>"
+  echo ""
 }
 
 core() {
@@ -11,12 +12,28 @@ core() {
     exit 0
   fi
 
-  local version=$1  
-  install $version
+  install "$@"
+  if [ "$?" != "0" ]; then
+    log::error "[$(timstamp)] failed to install ${PACKAGE_NAME}."
+    return 1
+  fi
+
+  log::success "[$(timstamp)] succeed to install ${PACKAGE_NAME}."
 }
 
 run() {
-  core $@
+  core "$@"
 }
 
-run $@
+if [ "$1" = "ONE_LINE" ]; then
+  command -v zmicro >>/dev/null 2>&1
+  if [ $? -ne 0 ]; then
+    curl -o- https://raw.githubusercontent.com/zcorky/zmicro/master/install | sh
+  fi
+
+  zmicro package install docker
+else
+  set -e
+
+  run "$@"
+fi
